### PR TITLE
Added 64-pin MZ support. Fixed numerous warnings.

### PR DESCRIPTION
**Pull request by majenkotech**
* A new macro `__PIC32_PINS__` has been added to the cpudefs tables.  This
  allows you to select such things as the correct starting address for
  remappable pins on devices which lack a port A.  The 64-pin MZ variants
  have been fixed using this method.

* Numerous compilation warnings have been removed. This includes changing
  all the `char *` function parameters in Stream to be `const char *`, some
  brackets around some macro arithmetic, and some extra casts and hints to
  variables and assignments.  Also some unused variables have been commented
  out.

### CODE REVIEW

**Comment by majenkotech** [comment]
Any progress on merging these changes?

**Comment by ricklon** [comment]
Everyone happy enough? Can we make refinements to this later?

--Rick

On Sat, Jan 24, 2015 at 6:14 AM, Matt Jenkins <notifications@github.com>
wrote:

> Any progress on merging these changes?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/chipKIT32/chipKIT32-MAX/pull/542#issuecomment-71311642>
> .
>



-- 
Co-founder
Fair Use Building and Research (FUBAR) Labs
http://fubarlabs.org

**Comment by EmbeddedMan** [comment]
I don't have any fundamental problem with any of the changes. They all seem like good ideas. However, I'm not knowledgeable enough to understand if they are all correct off the top of my head. Is Keith getting these GitHub e-mails? If he isn't, he should be. He knows more about MZ support than just about anybody, and should probably double check this. Or we can just merge it in, and see if anything bad happens and fit it later. I'm OK with either.

**Comment by ricklon** [comment]
Good question. His feedback should be in the pull request history. I've got some feedback from Keith. There are a few things that he would like changed, but they could be done after the pull request.

**Comment by majenkotech** [comment]
If they are related to the 8-bit/16-bit tables change, that has already been addressed and changed to be done properly.

**Pull request merged**
