### PR TITLE
break out boards.txt into variants

### PR DESCRIPTION
**Pull request by KeithV**
Also fixed EEPROM for MZ and added uC32 / Uno32 Pmod Variants

### CODE REVIEW

**Comment by KeithV** [comment]
All created unsupported_boards.txt with obsolete boards

**Comment by KeithV** [comment]
Thanks Brian

 

Can you do a windows build so I can check it out?

 

KeithV

**Comment by EmbeddedMan** [comment]
Keith,

Already done.
https://chipkit.s3.amazonaws.com/builds/mpide-0150-windows-20150103-test.zip

Have at it.

*Brian

**Comment by KeithV** [comment]
Thanks!

**Pull request merged**
