### PR TITLE
Group .sdata input sections

### PR DESCRIPTION
**Pull request by jasonkajita**
Group .sdata input sections into the .sdata output section in hardware/pic32/cores/pic32/chipKIT-application-COMMON.ld

Address https://github.com/chipKIT32/chipKIT32-MAX/issues/589

### CODE REVIEW

**Comment by jasonkajita** [comment]
hmm, not sure if I did this pull request correctly. Why are there so many commits?

**Comment by majenkotech** [comment]
You may have been working from a slightly older repo or something - the main thing is there is only one changed file with your modifications in it.

**Comment by adamwolf** [comment]
hey @chipkitbot, this is ok to test

**Comment by ricklon** [comment]
Did this get straightened out? You might amend the commit.

**Pull request merged**
