### PR TITLE
Created DMA abstraction system

### PR DESCRIPTION
**Pull request by majenkotech**
This allows you to "ask" the core for a DMA channel to do DMA operations with.  You can give it a preferred channel that you would like to use, and if that channel is available it will give it to you - otherwise it will find an unused one.

**I have also changed the MZ's ADC code to use this abstraction. It appears to work on my WiFire fine, but needs some thorough testing by someone that knows the MZ ADC inside out before it gets released.**

New core functions:

* `int dma_acquire();`

Ask for any available channel - equivalent to `dma_acquire_pref(0)`

* `int dma_acquire_pref(int pref);`

Try and get a preferred channel if available, or any channel that's available if not.

* `int dma_release(int chan);`

Give up a channel after you have finished with it

* `int dma_busy(int chan);`

True if a channel is currently busy (actively transferring data)

* `void *dma_memcpy(int chan, void *dest, const void *src, size_t n);`

DMA equivalent to memcpy().

* `int dma_transfer(int chan, void *dest, const void *src, int dsize, int ssize, int csize, int irq);`

Configure an interrupt-driven transfer (usually to/from a peripheral).

* `int dma_block_finished(int chan);`

Find if a requested block transfer has finished.

* `p32_dch *dma_registers(int chan);`

Get the raw registers for your channel.

There is also a variable tag `__DMA` which is basically a shortcut for `__attribute__((coherent))`.

### CODE REVIEW

**Comment by ricklon** [comment]
Matt, did you get the feedback from Keith? How do you want to procede?

**Comment by majenkotech** [comment]
Yes I did. I'm making some changes to it and releasing a new commit soon.

**Comment by ricklon** [comment]
I just saw you made this update. All set?

**Comment by JacobChrist** [comment]
This is awesome, if I would have anything to suggest is that the API be more Arduino.  Do that the that you would use it like an object.

DMA.Begin()...

DMA.Aquire()

ect...

Take my suggestions with a grain of salt.

**Comment by adamwolf** [comment]
hey @chipkitbot this is ok to test

**Comment by ricklon** [comment]
Keith, has some code enabling 12bit adc. So he had some concerns that the there might be an ADC conflict. I don't really know for sure,but figured I would report it.

**Comment by adamwolf** [comment]
retest

**Comment by ricklon** [comment]
Matt, did this get moved to chipKIT-core?

The only concern I found was if the DMA interface changed the WiFire or
WF32  ADC code.

--Rick

On Wed, Sep 16, 2015 at 10:29 AM, Adam Wolf <notifications@github.com>
wrote:

> retest
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/chipKIT32/chipKIT32-MAX/pull/570#issuecomment-140758477>
> .
>



-- 
Co-founder
Fair Use Building and Research (FUBAR) Labs
http://fubarlabs.org

**Comment by majenkotech** [comment]
No, and it doesn't want to be yet.  It needs some extra tweaks and fixes when I finally get around to digging into it again.

**Comment by EmbeddedMan** [comment]
We're closing this PR, as Matt is going to be re-doing the code as per some of the comments above and re-submitting the PR in the future.

**Pull request closed without merging**
