### PR TITLE
Updated startup code with ISA switching code, vector spacing register, L1 cache init and FPU engine init

### PR DESCRIPTION
**Pull request by mariusgeanta**
Issue #593.
Also modified platforms.txt to pass startup routine directly to the linker, issue #591.

### CODE REVIEW

**Comment by majenkotech** [comment]
ok to test

**Comment by adamwolf** [comment]
test this please

**Comment by EmbeddedMan** [comment]
Is there a link generated to the build outputs of chipkitbot? It would be
really cool if it would just show up in this e-mail chain . . .

*Brian

**Comment by ricklon** [comment]
If the link was added to the response template. Then we can click and check
out each build.
--Rick

On Fri, Oct 2, 2015 at 9:20 AM, Brian Schmalz <notifications@github.com>
wrote:

> Is there a link generated to the build outputs of chipkitbot? It would be
> really cool if it would just show up in this e-mail chain . . .
>
> *Brian
>
> On Fri, Oct 2, 2015 at 8:13 AM, Adam Wolf <notifications@github.com>
> wrote:
>
> > test this please
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/chipKIT32/chipKIT32-MAX/pull/613#issuecomment-145016470
> >
> > .
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/chipKIT32/chipKIT32-MAX/pull/613#issuecomment-145018676>
> .
>



-- 
Co-founder
Fair Use Building and Research (FUBAR) Labs
http://fubarlabs.org

**Comment by adamwolf** [comment]
I would like it to post a comment comment to the thread saying success with
a link to the artifacts, or failure with a link to the test log or console
output.

I will take a look, and file an issue on the plugin if this is not doable
yet.

Adam Wolf

**Comment by ricklon** [comment]
Is this conflict resolved?

**Comment by EmbeddedMan** [comment]
Nope. Waiting on Jason or author to resolve conflicts before it can be
merged.

*Brian

**Comment by EmbeddedMan** [comment]
retest this please

**Comment by EmbeddedMan** [comment]
Marius, Thanks so much for fixing this PR up. I'll be mering it in shortly - we're having some issues with the chipkitbot builder, and using this PR to test/fix those issues. That's why we're not merging it in right away.

**Comment by adamwolf** [comment]
retest this please

**Comment by adamwolf** [comment]
So, @EmbeddedMan, this build did that weird thing we've seen before where it has the different name zip.  I adjusted the filter to pull in those other names, but I'm kinda curious why it does that.

retest this please

**Comment by adamwolf** [comment]
retest this please

**Comment by adamwolf** [comment]
There we go, @EmbeddedMan.  I think I've gotten it.  If you update a PR after chipkitbot builds it once, it has a different name than if you don't.  The job wasn't detecting that new name as a success.  I added it.

(There is also the ongoing problem of chipkitbot ignoring your commands, but I guess a robot listens to his father first?  I'll keep looking into that.)

**Comment by EmbeddedMan** [comment]
Adam, I never received any e-mail about this latest build being successful, so I can't download it from chipkitbot and test it. Could you post the link here? I want to test this change out before I merge it into master.

**Comment by adamwolf** [comment]
test this please

**Comment by EmbeddedMan** [comment]
I tested this PR before it was merged. While I don't have enough knowledge to test out that the changes in the PR worked as intended, I have confirmed that they don't screw up the compilation of a normal sketch. (On an Uno32)

**Pull request merged**
